# backstage.yaml

apiVersion: backstage.io/v1
kind: Location
metadata:
  name: github-repo
spec:
  type: url
  targets:
    - https://github.com/VENKATRAMMADHIRI/Backstage1/blob/main/catalog-info.yaml
  rules:
    - allow:
        - template
