# Sample Backstage Template YAML

apiVersion: backstage.io/v1
kind: Template
metadata:
  name: sample-template
title: Sample Backstage Template
description: A template for creating a sample service in Backstage

spec:
  type: service

  # Define steps
  steps:
    - id: create
      name: Create Service
      script: echo "Creating the sample service..."

    - id: deploy
      name: Deploy Service
      script: echo "Deploying the sample service..."

    - id: test
      name: Test Service
      script: echo "Running tests on the sample service..."

    - id: publish
      name: Publish Service
      script: echo "Publishing the sample service..."

  # Define inputs
  inputs:
    - type: text
      title: Service Name
      name: serviceName
      description: Enter the name of the service
    - type: text
      title: Repository URL
      name: repositoryUrl
      description: Enter the repository URL
